### PR TITLE
fixed readme to account for docker-compose issue

### PR DESCRIPTION
**Pull request by puja108**
the docker-compose-yml needs to be changed manually as it does not
support variables

### CODE REVIEW

**Comment by puja108** [comment]
workaround for https://github.com/giantswarm/giantswarm-firstapp-java/issues/6

RFR @luebken

**Comment by luebken** [comment]
Why not remove the `image` declaration? Like in https://github.com/giantswarm/giantswarm-firstapp-go/blob/master/fig.yml

The drawback would be you can't use the same image from `docker-compose` pushing it to Giant Swarm. But than again we have the Makefile handling this.

**Comment by puja108** [comment]
Didn't think of the build feature, first thought it would be slow, but docker should be caching the layers anyway, so I will try that now.

Yeah, I think it's ok to be building a new image for pushing it, as the caching should keep that fast.

**Comment by puja108** [comment]
works with build . now (a bit slower, but ok) /ping @luebken

**Comment by puja108** [comment]
will fix some more small issues based on discussion with @luebken

**Comment by puja108** [comment]
included the changes we talked about on Friday. RFR @luebken

**Comment by luebken** [comment]
Didn't test it but LGTM

**Pull request merged**
